const categories = [
    { 'name': 'Ausgehen', 'icon': 'fa-glass' },
    { 'name': 'Auslagen', 'icon': 'fa-pencil-square-o' },
    { 'name': 'Digitales', 'icon': 'fa-laptop' },
    { 'name': 'Digitales > Apps', 'icon': 'fa-steam' },
    { 'name': 'Digitales > Services', 'icon': 'fa-paypal' },
    { 'name': 'Digitales > Server/Domains', 'icon': 'fa-server' },
    { 'name': 'Digitales > Telefon', 'icon': 'fa-phone' },
    { 'name': 'Fahrkosten', 'icon': 'fa-car' },
    { 'name': 'Fahrkosten > Auto', 'icon': 'fa-car' },
    { 'name': 'Fahrkosten > ÖPNV', 'icon': 'fa-bus' },
    { 'name': 'Gebühren', 'icon': 'fa-money' },
    { 'name': 'Gebühren > Beitragsservice', 'icon': 'fa-tv' },
    { 'name': 'Gebühren > Studiengebühren', 'icon': 'fa-university' },
    { 'name': 'Gebühren > Strafzettel', 'icon': 'fa-dollar' },
    { 'name': 'Gebühren > Steuern', 'icon': 'fa-dollar' },
    { 'name': 'Gebühren > Versicherungen', 'icon': 'fa-pencil-square-o' },
    { 'name': 'Gebühren > Bankgebühren', 'icon': 'fa-credit-card' },
    { 'name': 'Geschenke', 'icon': 'fa-gift' },
    { 'name': 'Gesundheit', 'icon': 'fa-heartbeat' },
    { 'name': 'Gesundheit > Arztkosten', 'icon': 'fa-hospital-o' },
    { 'name': 'Gesundheit > Medikamente', 'icon': 'fa-medkit' },
    { 'name': 'Haushalt', 'icon': 'fa-bath' },
    { 'name': 'Hobby', 'icon': 'fa-flask' },
    { 'name': 'Kleidung', 'icon': 'fa-graduation-cap' },
    { 'name': 'Lebensmittel', 'icon': 'fa-shopping-basket' },
    { 'name': 'Reisen', 'icon': 'fa-map-marker' },
    { 'name': 'Sonstiges', 'icon': 'fa-leaf' },
    { 'name': 'Technik', 'icon': 'fa-microchip' },
    { 'name': 'Wohnen', 'icon': 'fa-home' },
    { 'name': 'Wohnen > Einrichtung', 'icon': 'fa-bed' },
    { 'name': 'Wohnen > Miete', 'icon': 'fa-home' },
    { 'name': 'Wohnen > Nebenkosten', 'icon': 'fa-shower' }
]

export default categories
